version: "3.9"
services:
  web:
    build: .
    init: true
    image: bigarmsclub:latest
    ports:
      - 8000:8000
    environment:
      - ENDPOINT_URL=http://dynamo:8888
    volumes:
      - ./bigarms:/app
    command: ["uvicorn", "bigarms.leaderboard:app", "--host", "0.0.0.0", "--reload", "--reload-dir", "./bigarms"]
    depends_on:
      - dynamo
      - migrations

  dynamo:
    image: amazon/dynamodb-local
    volumes:
      - ./data/:/home/dynamodblocal/data
    ports:
      - 8888:8888
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/home/dynamodblocal/data", "-port", "8888"]

  migrations:
    image: python:3.8.9-buster
    environment:
      - BASE_DIR=.
      - AWS_ACCESS_KEY_ID=DUMMYIDEXAMPLE
      - AWS_SECRET_ACCESS_KEY=DUMMYEXAMPLEKEY
      - ENDPOINT_URL=http://dynamo:8888
    working_dir: /app
    volumes:
     - ./Makefile:/app/Makefile
     - ./Make.defs:/app/Make.defs
     - ./Make.rules:/app/Make.rules
     - ./scripts:/app/scripts
     - ./requirements:/app/requirements
    command: ["/app/scripts/wait-for-it.sh", "dynamo:8888", "-t", "20", "--", "make", "fixtures"]

  lambda-reply:
    image: lambci/lambda:python3.8
    volumes:
     - ./bigarms:/var/task:ro,delegated
     - ./deployment/venv/lib/python3.8/site-packages:/opt/python:ro,delegated
    environment:
      - DOCKER_LAMBDA_STAY_OPEN=1
      - ENDPOINT_URL=http://dynamo:8888
    env_file:
      - twilio.test.env
    ports:
      - 9001:9001
    command: ["actionlog.lambda_function.lambda_handler"]

  lambda-api:
    image: lambci/lambda:python3.8
    volumes:
     - ./bigarms:/var/task:ro,delegated
     - ./deployment/venv/lib/python3.8/site-packages:/opt/python:ro,delegated
    environment:
      - DOCKER_LAMBDA_STAY_OPEN=1
      - ENDPOINT_URL=http://dynamo:8888
    env_file:
      - twilio.test.env
    ports:
      - 9002:9001
    command: ["bigarms.leaderboard.handler"]

  package:
    image: lambci/lambda:build-python3.8
    volumes:
     - ./:/var/task
     - ./requirements:/requirements:ro,delegated
    entrypoint: ""
    command: ["make", "-C", "package"]