---

Description:
    Deploy a dynamodb table for storing bigarms messages

Resources:
    DDBTableLogEntry:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: !Sub ${AWS::StackName}-entry
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          -
            AttributeName: "member_id"
            AttributeType: "S"
          -
            AttributeName: "time_created"
            AttributeType: "N"
        KeySchema:
          -
            AttributeName: "member_id"
            KeyType: "HASH"
          -
            AttributeName: "time_created"
            KeyType: "RANGE"

    DDBTableStats:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: !Sub ${AWS::StackName}-statistics
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          -
            AttributeName: "member_id"
            AttributeType: "S"
          -
            AttributeName: "entry_count"
            AttributeType: "N"
          -
            AttributeName: "time_updated"
            AttributeType: "N"
        KeySchema:
          -
            AttributeName: "member_id"
            KeyType: "HASH"
          -
            AttributeName: "entry_count"
            KeyType: "RANGE"
        GlobalSecondaryIndexes:
          -
            IndexName: "activity-index"
            KeySchema:
              -
                AttributeName: "member_id"
                KeyType: "HASH"
              -
                AttributeName: "time_updated"
                KeyType: "RANGE"
            Projection:
                NonKeyAttributes: []
                ProjectionType: "ALL"